const musicItems = [{
        id: '1',
        song: 'Thích thì đến',
        singers: ['Lê Bảo Bình'],
        link: '/musics/THÍCH THÌ ĐẾN - LÊ BẢO BÌNH - id_1.mp3',
        imageLink: '/images/singerImages/LeBaoBinh.jpg',
        type: 'Việt Nam',
    },
    {
        id: '2',
        song: 'Cứ ngỡ là anh',
        singers: ['Đinh Tùng Huy'],
        link: '/musics/Cu Ngo La Anh - Dinh Tung Huy id_2.mp3',
        imageLink: '/images/singerImages/DinhTungHuy.jpg',
        type: 'Việt Nam',
    },
    {
        id: '3',
        song: 'As long as you love me',
        singers: ['Justin Bieber'],
        link: '/musics/AsLongAsYouLoveMe-Justin Bieber - id_3.mp3',
        imageLink: '/images/singerImages/JustinBieber.jpg',
        type: 'US-UK',
    },
    {
        id: '4',
        song: 'Sold out',
        singers: ['Hawk Nelson'],
        link: '/musics/Sold Out - Hawk Nelson - id_4 .mp3',
        imageLink: '/images/singerImages/Hawk Nelson.jpg',
        type: 'US-UK',
    },
    {
        id: '5',
        song: 'Bad Liar',
        singers: ['Imagine Dragons'],
        link: '/musics/Bad Liar - Imagine Dragons - id_5.mp3',
        imageLink: '/images/singerImages/Imagine Dragons.jpg',
        type: 'US-UK',
    },
    {
        id: '6',
        song: 'Tình yêu hoa gió',
        singers: ['Trương Thế Vinh'],
        link: '/musics/TÌNH YÊU HOA GIÓ - TRƯƠNG THẾ VINH - id_6.mp3',
        imageLink: '/images/singerImages/TruongTheVinh.jpg',
        type: 'Việt Nam',
    },
    {
        id: '7',
        song: 'Sợ rằng em biết anh còn yêu em',
        singers: ['Juun Dăng Dũng'],
        link: '/musics/SỢ RẰNG EM BIẾT ANH CÒN YÊU EM - JUUN ĐĂNG DŨNG id_7.mp3',
        imageLink: '/images/singerImages/Juun Dăng Dũng.jpg',
        type: 'Việt Nam',
    },
    {
        id: '8',
        song: 'All I got',
        singers: ['Said The Sky & Kwesi'],
        link: '/musics/All I Got - Said The Sky & Kwesi - id_8.mp3',
        imageLink: '/images/singerImages/Said The Sky & Kwesi.jpeg',
        type: 'US-UK',
    },
    {
        id: '9',
        song: 'The way I still love you',
        singers: ['Reynard Silva'],
        link: '/musics/The way I still love you - Reynard Silva - id_9.mp3',
        imageLink: '/images/singerImages/Reynard Silva.jpg',
        type: 'US-UK',
    },
    {
        id: '10',
        song: 'Đau Bởi Vì Ai',
        singers: ['Nhật Phong'],
        link: '/musics/Đau Bởi Vì Ai - Nhật Phong - 10.mp3',
        imageLink: '/images/singerImages/Nhật phong.jpg',
        type: 'Việt Nam',
    },
    {
        id: '11',
        song: 'Về bên Anh',
        singers: ['Jack'],
        link: '/musics/VỀ BÊN ANH - Jack - 11.mp3',
        imageLink: '/images/singerImages/Jack.jpg',
        type: 'Việt Nam',
    },
    {
        id: '12',
        song: 'Em Ổn Không',
        singers: ['Trịnh Thiên Ân', 'ViruSs', 'Láo Soái Nhi'],
        link: '/musics/Em Ổn Không - Trịnh Thiên Ân x ViruSs x Láo Soái Nhi - 12.mp3',
        imageLink: '/images/singerImages/Trịnh Thiên Ân.jpg',
        type: 'Việt Nam',
    },
    {
        id: '13',
        song: 'Cô Đơn Sẽ Tốt Hơn',
        singers: ['Lương Gia Hùng'],
        link: '/musics/Cô Đơn Sẽ Tốt Hơn - Lương Gia Hùng -13.mp3',
        imageLink: '/images/singerImages/Lương Gia Hùng.jpg',
        type: 'Việt Nam',
    },
    {
        id: '14',
        song: 'Phụ Tình',
        singers: ['Trịnh Đình Quang'],
        link: '/musics/Phụ Tình - Trịnh Đình Quang - 14.mp3',
        imageLink: '/images/singerImages/Trịnh Đình Quang.jpg',
        type: 'Việt Nam',
    },
    {
        id: '15',
        song: 'Khóc Cùng Em',
        singers: ['Mr. Siro'],
        link: '/musics/Khóc Cùng Em - Mr. Siro x Gray x Wind - 15.mp3',
        imageLink: '/images/singerImages/Mr Siro.jpg',
        type: 'Việt Nam',
    },
    {
        id: '16',
        song: 'Hỏi Thăm Nhau',
        singers: ['Lê Bảo Bình'],
        link: '/musics/Hỏi Thăm Nhau - Lê Bảo Bình -16.mp3',
        imageLink: '/images/singerImages/LeBaoBinh.jpg',
        type: 'Việt Nam',
    },
    {
        id: '17',
        song: 'Yêu',
        singers: ['Khắc Việt'],
        link: '/musics/Yêu - Khắc Việt - 17.mp3',
        imageLink: '/images/singerImages/Khắc Việt.jpg',
        type: 'Việt Nam',
    },
    {
        id: '18',
        song: 'Gọi tên em trong đêm',
        singers: ['The Men'],
        link: '/musics/Gọi tên em trong đêm - The Men - 18.mp3',
        imageLink: '/images/singerImages/The Men.jpg',
        type: 'Việt Nam',
    },
    {
        id: '19',
        song: 'Thất Tình',
        singers: ['Trịnh Đình Quang'],
        link: '/musics/Thất Tình - Trịnh Đình Quang - 19.mp3',
        imageLink: '/images/singerImages/Trịnh Đình Quang.jpg',
        type: 'Việt Nam',
    },
    {
        id: '20',
        song: 'Đường Một Chiều',
        singers: ['Huỳnh Tú'],
        link: '/musics/Đường Một Chiều - Huỳnh Tú - 20.mp3',
        imageLink: '/images/singerImages/Huỳnh Tú.jpg',
        type: 'Việt Nam',
    },
    {
        id: '21',
        song: 'Buồn Lắm Em Ơi',
        singers: ['Trịnh Đình Quang'],
        link: '/musics/Buồn Lắm Em Ơi - Trịnh Đình Quang - 21.mp3',
        imageLink: '/images/singerImages/Trịnh Đình Quang.jpg',
        type: 'Việt Nam',
    },
    {
        id: '22',
        song: 'Thế Giới Ảo Tình Yêu Thật',
        singers: ['Trịnh Đình Quang'],
        link: '/musics/Thế Giới Ảo Tình Yêu Thật - Trịnh Đình Quang 22.mp3',
        imageLink: '/images/singerImages/Trịnh Đình Quang.jpg',
        type: 'Việt Nam',
    },
    {
        id: '23',
        song: 'Tháng Tư Là Lời Nối Dối Của Em',
        singers: ['Hà Anh Tuấn'],
        link: '/musics/23 - Tháng Tư Là Lời Nối Dối Của Em - Hà Anh Tuấn.mp3',
        imageLink: '/images/singerImages/Hà Anh Tuấn.jpg',
        type: 'Việt Nam',
    },
    {
        id: '24',
        song: 'Lạ Lùng',
        singers: ['Vũ'],
        link: '/musics/24 - LẠ LÙNG - Vũ.mp3',
        imageLink: '/images/singerImages/Vũ.png',
        type: 'Việt Nam',
    },
    {
        id: '25',
        song: 'Đông Kiếm Em',
        singers: ['Vũ'],
        link: '/musics/25 - Đông Kiếm Em - Vũ.mp3',
        imageLink: '/images/singerImages/Vũ.png',
        type: 'Việt Nam',
    },
    {
        id: '26',
        song: 'Hết Thương Cạn Nhớ',
        singers: ['Đức Phúc'],
        link: '/musics/26 - Hết Thương Cạn Nhớ - Đức Phúc.mp3',
        imageLink: '/images/singerImages/Đức Phúc.jpg',
        type: 'Việt Nam',
    },
    {
        id: '27',
        song: 'Đừng Nói',
        singers: ['Đình Dũng'],
        link: '/musics/27 - Đừng Nói - Đình Dũng.mp3',
        imageLink: '/images/singerImages/Đình Dũng.jpg',
        type: 'Việt Nam',
    },
    {
        id: '28',
        song: 'Thu cuối',
        singers: ['Yanbi'],
        link: '/musics/28 - thu cuối Mr.T ft Yanbi & Hằng BingBoong.mp3',
        imageLink: '/images/singerImages/Yanbi.png',
        type: 'Việt Nam',
    },
    {
        id: '29',
        song: 'Truyền Thái Y',
        singers: ['Ngô Kiến Huy'],
        link: '/musics/29 - Truyền Thái Y - Ngô Kiến Huy x Masew x Đình Hà Uyên Thư.mp3',
        imageLink: '/images/singerImages/Ngô Kiến Huy.jpg',
        type: 'Việt Nam',
    },
    {
        id: '30',
        song: 'Tâm Ma',
        singers: ['BlackBi'],
        link: '/musics/30 - Tâm Ma - BlackBi ft Võ Đình Hiếu ft Elb - MV Lyrics.mp3',
        imageLink: '/images/singerImages/BlackBi.jpg',
        type: 'Việt Nam',
    },
    {
        id: '31',
        song: 'Anh thanh niên',
        singers: ['HuyR'],
        link: '/musics/31 - Anh thanh niên - HuyR .mp3',
        imageLink: '/images/singerImages/HuyR.jpg',
        type: 'Việt Nam',
    },
    {
        id: '32',
        song: 'Nothing In Your Eyes',
        singers: ['Yanbi', 'Mr.T', 'Hà Bi'],
        link: '/musics/32 - Nothing In Your Eyes - Mr.T ft Yanbi & Hà Bi.mp3',
        imageLink: '/images/singerImages/Yanbi.png',
        type: 'Việt Nam',
    },
    {
        id: '33',
        song: 'Nothing In Your Eyes 2',
        singers: ['Yanbi', 'Mr.T', 'Bảo Thy'],
        link: '/musics/33 - Nothing In Your Eyes 2 - Mr.T ft Yanbi & Bảo Thy.mp3',
        imageLink: '/images/singerImages/Bao Thy.jpg',
        type: 'Việt Nam',
    },
    {
        id: '34',
        song: '24H',
        singers: ['LyLy'],
        link: '/musics/34 - 24H - LyLy ft. Magazine.mp3',
        imageLink: '/images/singerImages/LyLy.jpg',
        type: 'Việt Nam',
    },
    {
        id: '35',
        song: 'Tận Cùng Nỗi Nhớ',
        singers: ['Will'],
        link: '/musics/35 - Tận Cùng Nỗi Nhớ - Will.mp3',
        imageLink: '/images/singerImages/Will.jpg',
        type: 'Việt Nam',
    },
    {
        id: '36',
        song: 'Người Nào Đó',
        singers: ['JustaTee'],
        link: '/musics/36 - Người Nào Đó - JustaTee.mp3',
        imageLink: '/images/singerImages/JustaTee.jpg',
        type: 'Việt Nam',
    },
    {
        id: '37',
        song: 'She Neva Knows',
        singers: ['JustaTee'],
        link: '/musics/37 - She Neva Knows - JustaTee.mp3',
        imageLink: '/images/singerImages/JustaTee.jpg',
        type: 'Việt Nam',
    },
    {
        id: '38',
        song: 'Yêu Một Người Có Lẽ',
        singers: ['Lou Hoàng', 'Miu Lê'],
        link: '/musics/38 - Yêu Một Người Có Lẽ - Lou Hoàng - Miu Lê.mp3',
        imageLink: '/images/singerImages/Lou Hoàng.jpg',
        type: 'Việt Nam',
    },
    {
        id: '39',
        song: 'Mình là gì của nhau',
        singers: ['Lou Hoàng'],
        link: '/musics/39 - Mình là gì của nhau -Lou Hoàng.mp3',
        imageLink: '/images/singerImages/Lou Hoàng.jpg',
        type: 'Việt Nam',
    },
    {
        id: '40',
        song: 'Cảm giác lúc ấy sẽ ra sao',
        singers: ['Lou Hoàng'],
        link: '/musics/40 - CẢM GIÁC LÚC ẤY SẼ RA SAO - LOU HOÀNG.mp3',
        imageLink: '/images/singerImages/Lou Hoàng.jpg',
        type: 'Việt Nam',
    },
    {
        id: '41',
        song: 'Là Bạn Không Thể Yêu',
        singers: ['Lou Hoàng'],
        link: '/musics/41 - Là Bạn Không Thể Yêu - Lou Hoàng.mp3',
        imageLink: '/images/singerImages/Lou Hoàng.jpg',
        type: 'Việt Nam',
    },
    {
        id: '42',
        song: 'Nếu ngày ấy',
        singers: ['Soobin Hoàng Sơn'],
        link: '/musics/42 - NẾU NGÀY ẤY - SOOBIN HOÀNG SƠN.mp3',
        imageLink: '/images/singerImages/Soobin Hoàng Sơn.jpg',
        type: 'Việt Nam',
    },
    {
        id: '43',
        song: 'Bâng Khuâng',
        singers: ['JustaTee'],
        link: '/musics/43 - Bâng Khuâng - JustaTee.mp3',
        imageLink: '/images/singerImages/JustaTee.jpg',
        type: 'Việt Nam',
    },
    {
        id: '44',
        song: 'Suýt nữa thì',
        singers: ['Andiez'],
        link: '/musics/44 - SUÝT NỮA THÌ - OFFICIAL OST - ANDIEZ x BITI\'S HUNTER.mp3',
        imageLink: '/images/singerImages/Andiez.jpg',
        type: 'Việt Nam',
    },
    {
        id: '45',
        song: 'Buồn Thì Cứ Khóc Đi',
        singers: ['Lynk Lee'],
        link: '/musics/45 - Buồn Thì Cứ Khóc Đi - Lynk Lee.mp3',
        imageLink: '/images/singerImages/Lynk Lee.jpg',
        type: 'Việt Nam',
    },
    {
        id: '46',
        song: 'Crying Over You',
        singers: ['JustaTee'],
        link: '/musics/46 - Crying Over You - JustaTee ft. Binz.mp3',
        imageLink: '/images/singerImages/JustaTee.jpg',
        type: 'Việt Nam',
    },
    {
        id: '47',
        song: 'Ai Đợi Mình Được Mãi',
        singers: ['Thanh Hưng'],
        link: '/musics/47 - Ai Đợi Mình Được Mãi - Thanh Hưng.mp3',
        imageLink: '/images/singerImages/Thanh Hưng.jpg',
        type: 'Việt Nam',
    },
    {
        id: '48',
        song: 'Anh Thương Em Em Thương Ai',
        singers: ['Đinh Tùng Huy'],
        link: '/musics/48 - Anh Thương Em Em Thương Ai - Đinh Tùng Huy.mp3',
        imageLink: '/images/singerImages/DinhTungHuy.jpg',
        type: 'Việt Nam',
    },
    {
        id: '49',
        song: 'Phía sau một cô gái',
        singers: ['Soobin Hoàng Sơn'],
        link: '/musics/49 - PHÍA SAU MỘT CÔ GÁI - Soobin Hoàng Sơn.mp3',
        imageLink: '/images/singerImages/Soobin Hoàng Sơn.jpg',
        type: 'Việt Nam',
    },
    {
        id: '50',
        song: 'Đi Để Trở Về',
        singers: ['Soobin Hoàng Sơn'],
        link: '/musics/50 - Đi Để Trở Về - Soobin Hoàng Sơn ll Azuie Nguyen.mp3',
        imageLink: '/images/singerImages/Soobin Hoàng Sơn.jpg',
        type: 'Việt Nam',
    },
    {
        id: '51',
        song: 'Anh Đã Khóc Vì Em',
        singers: ['Đinh Tùng Huy'],
        link: '/musics/51 - Anh Đã Khóc Vì Em - Đinh Tùng Huy.mp3',
        imageLink: '/images/singerImages/DinhTungHuy.jpg',
        type: 'Việt Nam',
    },
    {
        id: '52',
        song: 'Anh Đã Quen Với Cô Đơn',
        singers: ['Soobin Hoàng Sơn'],
        link: '/musics/52 - Anh Đã Quen Với Cô Đơn - Soobin Hoàng Sơn.mp3',
        imageLink: '/images/singerImages/Soobin Hoàng Sơn.jpg',
        type: 'Việt Nam',
    },
    {
        id: '53',
        song: 'Để Cho Anh Khóc',
        singers: ['Lê Bảo Bình'],
        link: '/musics/53 - Để Cho Anh Khóc - Lê Bảo Bình.mp3',
        imageLink: '/images/singerImages/LeBaoBinh.jpg',
        type: 'Việt Nam',
    },
    {
        id: '54',
        song: 'Là Ai Mang Nắng Đi Xa',
        singers: ['Yang'],
        link: '/musics/54 - Là Ai Mang Nắng Đi Xa - Yang.mp3',
        imageLink: '/images/singerImages/Yang.jpg',
        type: 'Việt Nam',
    },
    {
        id: '55',
        song: 'Ừ Có Anh Đây',
        singers: ['Tino'],
        link: '/musics/55 - Ừ Có Anh Đây - Tino.mp3',
        imageLink: '/images/singerImages/Tino.jpg',
        type: 'Việt Nam',
    },
    {
        id: '56',
        song: 'Cuộc Sống Em Ổn Không',
        singers: ['Anh Tú'],
        link: '/musics/56 - Cuộc Sống Em Ổn Không - Anh Tú The Voice.mp3',
        imageLink: '/images/singerImages/Anh Tú.jpg',
        type: 'Việt Nam',
    },
    {
        id: '57',
        song: 'Yêu vội vàng',
        singers: ['Lê Bảo Bình'],
        link: '/musics/57 - Yêu vội vàng - Lê Bảo Bình.mp3',
        imageLink: '/images/singerImages/LeBaoBinh.jpg',
        type: 'Việt Nam',
    },
    {
        id: '58',
        song: 'Đổi Thay',
        singers: ['Hồ Quang Hiếu'],
        link: '/musics/58 - Đổi Thay - Hồ Quang Hiếu.mp3',
        imageLink: '/images/singerImages/hồ Quang Hiếu.jpg',
        type: 'Việt Nam',
    },
    {
        id: '59',
        song: 'Trăm năm không quên',
        singers: ['Quang Hà'],
        link: '/musics/59 - TRĂM NĂM KHÔNG QUÊN - QUANG HÀ.mp3',
        imageLink: '/images/singerImages/Quang Hà.jpg',
        type: 'Việt Nam',
    },
    {
        id: '60',
        song: 'Tìm Lại Bầu Trời',
        singers: ['Tuấn Hưng'],
        link: '/musics/60 - Tìm Lại Bầu Trời - Tuấn Hưng.mp3',
        imageLink: '/images/singerImages/Tuấn Hưng.jpg',
        type: 'Việt Nam',
    },
    {
        id: '61',
        song: 'Bùa Yêu',
        singers: ['Bích Phương'],
        link: '/musics/61 - Bùa Yêu - Bích Phương.mp3',
        imageLink: '/images/singerImages/Bích Phương.jpg',
        type: 'Việt Nam',
    },
    {
        id: '62',
        song: 'Đi đu đưa đi',
        singers: ['Bích Phương'],
        link: '/musics/62 - Đi đu đưa đi - Bích Phương.mp3',
        imageLink: '/images/singerImages/Bích Phương.jpg',
        type: 'Việt Nam',
    },
    {
        id: '63',
        song: 'Bốn chữ lắm',
        singers: ['Trúc Nhân', 'Trương Thảo Nhi'],
        link: '/musics/63 - BỐN CHỮ LẮM - TRÚC NHÂN - TRƯƠNG THẢO NHI.mp3',
        imageLink: '/images/singerImages/Trúc Nhân.jpg',
        type: 'Việt Nam',
    },
    {
        id: '64',
        song: 'Ngồi hát đỡ buồn',
        singers: ['Trúc Nhân'],
        link: '/musics/64  - Ngồi hát đỡ buồn - Trúc Nhân.mp3',
        imageLink: '/images/singerImages/Trúc Nhân.jpg',
        type: 'Việt Nam',
    },
    {
        id: '65',
        song: 'Booty music',
        singers: ['Deepside'],
        link: '/musics/65 - Booty music - Deepside.mp3',
        imageLink: '/images/singerImages/Deepside.jpg',
        type: 'US-UK',
    },
    {
        id: '66',
        song: 'Whistle',
        singers: ['Flo Rida'],
        link: '/musics/66 - Whistle - Flo Rida.mp3',
        imageLink: '/images/singerImages/Flo Rida.jpg',
        type: 'US-UK',
    },
    {
        id: '67',
        song: 'Wake Me Up',
        singers: ['Avicii'],
        link: '/musics/67 - Avicii - Wake Me Up.mp3',
        imageLink: '/images/singerImages/Avicii.jpg',
        type: 'US-UK',
    },
    {
        id: '68',
        song: 'Tie Me Down',
        singers: ['Elley Duhé'],
        link: '/musics/68 - Gryffin, Elley Duhé - Tie Me Down.mp3',
        imageLink: '/images/singerImages/Elley Duhé.jpg',
        type: 'US-UK',
    },
    {
        id: '69',
        song: 'Tie Me Down x Faded x 8 Letters',
        singers: ['Elley Duhé'],
        link: '/musics/69 - Tie Me Down x Faded x 8 Letters.mp3',
        imageLink: '/images/singerImages/Elley Duhé.jpg',
        type: 'US-UK',
    },
    {
        id: '70',
        song: 'None Of My Busines',
        singers: ['Cher Lloyd'],
        link: '/musics/70 - None Of My Business - Cher Lloyd.mp3',
        imageLink: '/images/singerImages/Cher Lloyd.jpg',
        type: 'US-UK',
    },
    {
        id: '71',
        song: 'Criminal',
        singers: ['Britney Spears'],
        link: '/musics/71 - Criminal - Britney Spears.mp3',
        imageLink: '/images/singerImages/Britney Spears.jpg',
        type: 'US-UK',
    },
    {
        id: '72',
        song: 'Shape Of You',
        singers: ['Ed Sheeran'],
        link: '/musics/72 - Shape Of You - Ed Sheeran.mp3',
        imageLink: '/images/singerImages/Ed Sheeran.jpg',
        type: 'US-UK',
    },
    {
        id: '73',
        song: 'Send It',
        singers: ['Austin Mahone'],
        link: '/musics/73 - Send It - Austin Mahone ft. Rich Homie Quan.mp3',
        imageLink: '/images/singerImages/Austin Mahone.jpg',
        type: 'US-UK',
    },
    {
        id: '74',
        song: 'Twerk It Like Miley',
        singers: ['Brandon Beal'],
        link: '/musics/74 - Twerk It Like Miley - Brandon Beal.mp3',
        imageLink: '/images/singerImages/Brandon Beal.jpg',
        type: 'US-UK',
    },
    {
        id: '75',
        song: 'Rockabye',
        singers: ['Clean Bandit'],
        link: '/musics/75 - Rockabye - Clean Bandit.mp3',
        imageLink: '/images/singerImages/Clean Bandit.jpg',
        type: 'US-UK',
    },
    {
        id: '76',
        song: 'Pretty Girl',
        singers: ['Maggie Lindemann'],
        link: '/musics/76 - Pretty Girl - Maggie Lindemann.mp3',
        imageLink: '/images/singerImages/Maggie Lindemann.jpg',
        type: 'US-UK',
    },
    {
        id: '77',
        song: 'I\'m A Mess',
        singers: ['Bebe Rexha'],
        link: '/musics/77 -  i\'m A Mess - Bebe Rexha.mp3',
        imageLink: '/images/singerImages/Bebe Rexha.jpg',
        type: 'US-UK',
    },
    {
        id: '78',
        song: 'So Am I',
        singers: ['Ava Max'],
        link: '/musics/78 So Am I - Ava Max.mp3',
        imageLink: '/images/singerImages/Ava Max.jpg',
        type: 'US-UK',
    },
    {
        id: '79',
        song: 'Big Big World',
        singers: ['Emilia'],
        link: '/musics/79 - Big Big World - Emilia.mp3',
        imageLink: '/images/singerImages/Emilia.jpg',
        type: 'US-UK',
    },
    {
        id: '80',
        song: 'Sugar',
        singers: ['Maroon 5'],
        link: '/musics/80 - Sugar - Maroon 5.mp3',
        imageLink: '/images/singerImages/Maroon 5.jpg',
        type: 'US-UK',
    },
    {
        id: '81',
        song: 'Downtown',
        singers: ['Allie X'],
        link: '/musics/81 - Allie X - Downtown.mp3',
        imageLink: '/images/singerImages/Allie X.jpg',
        type: 'US-UK',
    },
    {
        id: '82',
        song: 'Wrap Me In Plastic',
        singers: ['CHROMANCE'],
        link: '/musics/82 - Wrap Me In Plastic - CHROMANCE.mp3',
        imageLink: '/images/singerImages/CHROMANCE.jpg',
        type: 'US-UK',
    },
    {
        id: '83',
        song: 'Sweet But Psycho',
        singers: ['Ava Max'],
        link: '/musics/83 - Sweet But Psycho - Ava Max.mp3',
        imageLink: '/images/singerImages/Ava Max.jpg',
        type: 'US-UK',
    },
    {
        id: '84',
        song: 'I Do',
        singers: ['911'],
        link: '/musics/84 - I Do - 911.mp3',
        imageLink: '/images/singerImages/911.jpg',
        type: 'US-UK',
    },
    {
        id: '85',
        song: 'Let me down slowly',
        singers: ['Alec Benjamin'],
        link: '/musics/85 - Let me down slowly - Alec Benjamin.mp3',
        imageLink: '/images/singerImages/Alec Benjamin.jpg',
        type: 'US-UK',
    },
    {
        id: '86',
        song: 'Impossible',
        singers: ['Shontelle'],
        link: '/musics/86 - Impossible - Shontelle.mp3',
        imageLink: '/images/singerImages/Shontelle.jpg',
        type: 'US-UK',
    },
    {
        id: '87',
        song: 'I\'m Not Her',
        singers: ['Clara Mae'],
        link: '/musics/87 - I\'m Not Her - Clara Mae.mp3',
        imageLink: '/images/singerImages/Clara Mae.jpg',
        type: 'US-UK',
    },
    {
        id: '88',
        song: 'Symphony',
        singers: ['Clean Bandit', 'Zara Larsson'],
        link: '/musics/88 - Symphony - Clean Bandit - Zara Larsson.mp3',
        imageLink: '/images/singerImages/Clean Bandit.jpg',
        type: 'US-UK',
    },
    {
        id: '89',
        song: 'Closer',
        singers: ['The Chainsmokers', 'Halsey'],
        link: '/musics/89 -  Closer - The Chainsmokers - Halsey.mp3',
        imageLink: '/images/singerImages/The Chainsmokers.jpg',
        type: 'US-UK',
    },
    {
        id: '90',
        song: 'Old Town Road',
        singers: ['Lil Nas X', ' Billy Ray Cyrus'],
        link: '/musics/90 - Old Town Road -  Lil Nas X - ft. Billy Ray Cyrus.mp3',
        imageLink: '/images/singerImages/Lil Nas X.jpg',
        type: 'US-UK',
    },
    {
        id: '91',
        song: 'Love Yourself',
        singers: ['Justin Bieber'],
        link: '/musics/91 - Love Yourself - Justin Bieber.mp3',
        imageLink: '/images/singerImages/JustinBieber.jpg',
        type: 'US-UK',
    },
    {
        id: '92',
        song: 'Way Back Home',
        singers: ['SHAUN'],
        link: '/musics/92 - Way Back Home - SHAUN (ft.Conor Maynard).mp3',
        imageLink: '/images/singerImages/SHAUN.jpg',
        type: 'Korean',
    },
    {
        id: '93',
        song: 'Something Just Like This',
        singers: ['The Chainsmokers'],
        link: '/musics/93 - Something Just Like This - The Chainsmokers & Coldplay.mp3',
        imageLink: '/images/singerImages/The Chainsmokers.jpg',
        type: 'US-UK',
    },
    {
        id: '94',
        song: 'Titanium',
        singers: ['Charlie Puth', 'Sia'],
        link: '/musics/94 - TITANIUM - David Guetta ft Sia.mp3',
        imageLink: '/images/singerImages/David Guetta.jpg',
        type: 'US-UK',
    },
    {
        id: '95',
        song: 'We Don\'t Talk Anymore',
        singers: ['Charlie Puth', 'Selena Gomez'],
        link: '/musics/95 - We Don\'t Talk Anymore - Charlie Puth (Ft. Selena Gomez).mp3',
        imageLink: '/images/singerImages/David Guetta.jpg',
        type: 'US-UK',
    },
    {
        id: '96',
        song: 'See You Again',
        singers: ['Wiz Khalifa', 'Charlie Puth'],
        link: '/musics/96 - See You Again - Wiz Khalifa ft. Charlie Puth.mp3',
        imageLink: '/images/singerImages/Charlie Puth.jpg',
        type: 'US-UK',
    },
    {
        id: '97',
        song: 'Bad guy',
        singers: ['Billie Eilish'],
        link: '/musics/97 - Bad guy - Billie Eilish.mp3',
        imageLink: '/images/singerImages/Billie Eilish.jpg',
        type: 'US-UK',
    },
    {
        id: '98',
        song: 'Memories',
        singers: ['Maroon 5'],
        link: '/musics/98 - Maroon 5 - Memories.mp3',
        imageLink: '/images/singerImages/Maroon 5.jpg',
        type: 'US-UK',
    },
    {
        id: '99',
        song: '2002',
        singers: ['Anne-Marie'],
        link: '/musics/99 - 2002 - Anne-Marie.mp3',
        imageLink: '/images/singerImages/Anne-Marie.jpg',
        type: 'US-UK',
    },
    {
        id: '100',
        song: 'Treat You Better',
        singers: ['Shawn Mendes'],
        link: '/musics/100 - Shawn Mendes - Treat You Better.mp3',
        imageLink: '/images/singerImages/Shawn Mendes.jpg',
        type: 'US-UK',
    },
]